version: "3.7"

services:
  postgres:
    image: postgres:11
    ports:
      - 5432:5432

  web:
    build: .
    command: “/opt/venv/bin/python app.py”
    volumes:
      - .:/parser
    depends_on:
      - postgres
    env_file:
      - .env